import type { Metadata } from "next";
import { Geist, Geist_Mono , Bebas_Neue} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";


const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ["latin"],
  variable: '--font-bebas-neue',
  display: 'swap',   // Add this line
  preload: false    // Add this line
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} overflow-x-hidden`}>
        <Navbar />
        <main className="overflow-x-hidden overflow-y-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}