import type { Metadata } from "next";
import { Geist, Geist_Mono , Bebas_Neue} from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";


const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ["latin"],
  variable: '--font-bebas-neue', // This makes the font available as a CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<div className="origin-top-left overflow-hidden">
      <html lang="en">
      <body         className={`${geistSans.variable} ${geistMono.variable} `}      >
        <Navbar />
        {children}  
        <Footer />
      </body>
    </html>
    </div>
  );
}
